version: "2"
run:
  go: "1.25"
  modules-download-mode: vendor
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - misspell
    - nakedret
    - nilerr
    # - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - wrapcheck
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    godot:
      #   declarations - for top level declaration comments (default);
      #   toplevel     - for top level comments;
      #   all          - for all comments.
      scope: toplevel
      exclude:
        - ^ \+.*
        - ^ ANCHOR.*
    importas:
      alias:
        # Kubernetes
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1
          alias: apiextensionsv1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
        - pkg: k8s.io/apimachinery/pkg/api/errors
          alias: apierrors
        - pkg: k8s.io/apimachinery/pkg/util/errors
          alias: kerrors
        - pkg: k8s.io/component-base/logs/api/v1
          alias: logsv1
        # Controller Runtime
        - pkg: sigs.k8s.io/controller-runtime
          alias: ctrl
      no-unaliased: true
    nolintlint:
      require-specific: true
      allow-unused: false
    revive:
      enable-all-rules: true
      rules:
        - name: dot-imports
          disabled: true
        # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#add-constant
        - name: add-constant
          arguments:
            - allowInts: 0,1,2,3,42,100
              allowStrs: '""'
              maxLitCount: "3"
          severity: warning
          disabled: true
        # More comments: Not converted
        - name: argument-limit
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity
          severity: warning
          disabled: true
        - name: cyclomatic
          arguments:
            - 10
          severity: warning
          disabled: true
        - name: defer
          arguments:
            - - call-chain
              - loop
              - method-call
              - recover
              - immediate-recover
              - return
          severity: warning
          disabled: false
        - name: exported
          severity: warning
          disabled: false
        - name: file-header
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-result-limit
          arguments:
            - 3
          severity: warning
          disabled: false
        - name: function-length
          arguments:
            - 15
            - 0
          severity: warning
          disabled: true
        - name: imports-blocklist
          arguments:
            - crypto/md5
            - crypto/sha1
          severity: warning
          disabled: false
        - name: line-length-limit
          arguments:
            - 120
          severity: warning
          disabled: true
        - name: max-public-structs
          arguments:
            - 3
          severity: warning
          disabled: true
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: false
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Println
          severity: warning
          disabled: false
        - name: var-naming
          arguments:
            - - ID
            - - VM
          severity: warning
          disabled: false
        # revive changed configuration
        - name: comment-spacings
          disabled: true
        - name: use-any
          disabled: true
        - name: deep-exit
          disabled: true
        - name: nested-structs
          disabled: true
        - name: struct-tag
          disabled: true
    staticcheck:
      checks:
        - all
        - -ST1006
      dot-import-whitelist:
        - github.com/onsi/gomega
        - github.com/onsi/ginkgo/v2
    usestdlibvars:
      # Suggest the use of http.MethodXX.
      # Default: true
      http-method: true
      # More comments, not converted ...
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
    wrapcheck:
      ignore-sigs:
        - status.Error(
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .Complete(
  exclusions:
    # We are disabling default golangci exclusions
    # because we want to help reviewers to focus on reviewing the most relevant
    # changes in PRs and avoid nitpicking.
    generated: lax
    rules:
      - linters:
          - wrapcheck
        path: _test\.go
    paths:
      - vendor$
      - test/vendor$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
  exclusions:
    generated: lax
    paths:
      - vendor$
      - test/vendor$
      - third_party$
      - builtin$
      - examples$
