project_name: csctl

builds:
  - binary: csctl
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X 'github.com/SovereignCloudStack/csctl/pkg/cmd.Version={{.Version}}'
      - -X 'github.com/SovereignCloudStack/csctl/pkg/cmd.Commit={{.Commit}}'
