apiVersion: infrastructure.cluster.x-k8s.io/v1alpha7
kind: OpenStackClusterTemplate
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Version }}-cluster
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      cloudName: gx-scs
      identityRef:
        name: cs-cluster-cloud-config
        kind: Secret
      apiServerLoadBalancer:
        enabled: true
      managedSecurityGroups: true
      nodeCidr: 10.8.0.0/20
      dnsNameservers:
      - 62.138.222.111
      - 62.138.222.222
      externalNetworkId: ebfe5546-f09f-4f42-ab54-094e457d42ec