name: Build csctl binary
# yamllint disable rule:line-length
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  manager-image:
    name: Build and push manager image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-go

      # Load Golang cache build from GitHub
      - name: build go binary
        run: |
          go build -o csctl main.go
