apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.96.0.0/12"]
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: openstack-ferrol-1-27-v4
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
      - name: imageRepository
        value: ""
    version: v1.27.8
    workers:
      machineDeployments:
        - class: workeramd64
          name: md-0
          replicas: 1
          failureDomain: nova
---
apiVersion: v1
data:
  clouds.yaml: ${OPENSTACK_CLOUD_YAML_B64} # cloud gx-scs
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: ${CLUSTER_NAME}-cloud-config
  namespace: "${NAMESPACE}"
